/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jFrames;

import DBManager.DatabaseManager;
import java.awt.Toolkit;
import java.sql.SQLException;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author IB
 */
public class ClassDetailsFrame extends javax.swing.JFrame {

    
    public ClassDetailsFrame() {
        initComponents();
        try {
            classesList.setListData(DatabaseManager.getClasses()); 
           } catch (SQLException ex) {
            ex.printStackTrace();
        }
    }

    private beans.ClassesBean getFieldsData() throws Exception{
       beans.ClassesBean bean=new beans.ClassesBean();
       bean.setClassName(classNameField.getText());
       bean.setClassNo(classKeywordField.getText());
       bean.setRemarks(remarksField.getText());
       bean.setStatus("1");
        return bean;
    }//End of getFieldsData method
   
   private void setFieldData(beans.ClassesBean bean){
       if(bean==null)return;
       classNameField.setText(bean.getClassName());
       classKeywordField.setText(bean.getClassNo());
       remarksField.setText(bean.getRemarks());
   }
   
   private void deleteClasses(){
       try{
            int class_id=((beans.ClassesBean)classesList.getSelectedValue()).getClassId();
            int rows=DatabaseManager.deleteClassesByClassId(class_id);
            if(rows>0)
              JOptionPane.showMessageDialog(null,"Data Update successfully..!!!");
              classesList.setListData(DatabaseManager.getClasses());
              clearFiled();
        }catch(Exception e){
            e.printStackTrace();
        }
   }
   
   private void clearFiled(){
      
       classesList.clearSelection();
         classNameField.setText("");
       classKeywordField.setText("");
       remarksField.setText("");
   }

   private void addClasses(){
    try{
      int row=DatabaseManager.addClasses(getFieldsData());
       if(row>0)
             JOptionPane.showMessageDialog(null,"Data Inserted!!!");
             classesList.setListData(DatabaseManager.getClasses());
        }catch(Exception e){
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, "Error while inserting error:"+e);
        }   
    }
   
   private void updateClasses(){
        try{
            if(classNameField.getText().equals("")){
             Toolkit.getDefaultToolkit().beep();   
             JOptionPane.showMessageDialog(this,"Kindly Select Class From List..."); return;}
            
            int class_id=((beans.ClassesBean)classesList.getSelectedValue()).getClassId();
            beans.ClassesBean bean=getFieldsData();
            bean.setClassId(class_id);
            
            int rows=DatabaseManager.updateClassesByClassId(bean, class_id);
            if(rows>0){
                Toolkit.getDefaultToolkit().beep();
               JOptionPane.showMessageDialog(null,"Data Update successfully..!!!");
             classesList.setListData(DatabaseManager.getClasses());
            }
        }catch(Exception e){
            e.printStackTrace();
        }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel62 = new javax.swing.JLabel();
        remarksField = new javax.swing.JTextField();
        addBtn1 = new javax.swing.JButton();
        classKeywordField = new javax.swing.JTextField();
        jLabel34 = new javax.swing.JLabel();
        classNameField = new javax.swing.JTextField();
        updateBtn1 = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        classesList = new javax.swing.JList<beans.ClassesBean>();
        deleteBtn1 = new javax.swing.JButton();
        clearBtn1 = new javax.swing.JButton();
        jLabel63 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        exitBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Class Details");
        setResizable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Class Details", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Courier New", 1, 12))); // NOI18N

        jLabel62.setFont(new java.awt.Font("Courier New", 1, 16)); // NOI18N
        jLabel62.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel62.setText("ClassKeyword:");

        remarksField.setFont(new java.awt.Font("Courier New", 1, 16)); // NOI18N

        addBtn1.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        addBtn1.setText("ADD");
        addBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBtn1ActionPerformed(evt);
            }
        });

        classKeywordField.setFont(new java.awt.Font("Courier New", 1, 16)); // NOI18N

        jLabel34.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        jLabel34.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel34.setText("ClassName:");

        classNameField.setFont(new java.awt.Font("Courier New", 1, 16)); // NOI18N
        classNameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                classNameFieldActionPerformed(evt);
            }
        });

        updateBtn1.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        updateBtn1.setText("UPDATE");
        updateBtn1.setEnabled(true);
        updateBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateBtn1ActionPerformed(evt);
            }
        });

        classesList.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        classesList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                classesListValueChanged(evt);
            }
        });
        jScrollPane5.setViewportView(classesList);

        deleteBtn1.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        deleteBtn1.setText("DELETE");
        deleteBtn1.setEnabled(true);
        deleteBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBtn1ActionPerformed(evt);
            }
        });

        clearBtn1.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        clearBtn1.setText("CLEAR");
        clearBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearBtn1ActionPerformed(evt);
            }
        });

        jLabel63.setFont(new java.awt.Font("Courier New", 1, 16)); // NOI18N
        jLabel63.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel63.setText("Remarks:");

        jLabel33.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        jLabel33.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel33.setText("Classes");

        exitBtn.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        exitBtn.setText("EXIT");
        exitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(addBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(updateBtn1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(deleteBtn1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(clearBtn1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(exitBtn))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(remarksField, javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel63)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jLabel62, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE)
                                            .addComponent(jLabel34, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGap(2, 2, 2)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(classKeywordField, javax.swing.GroupLayout.DEFAULT_SIZE, 381, Short.MAX_VALUE)
                                            .addComponent(classNameField))))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel33, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel33, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel34, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(classNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(classKeywordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel62, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel63, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(remarksField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(addBtn1)
                            .addComponent(updateBtn1)
                            .addComponent(deleteBtn1)
                            .addComponent(clearBtn1)
                            .addComponent(exitBtn)))
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void classesListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_classesListValueChanged
        setFieldData((beans.ClassesBean)classesList.getSelectedValue());
    }//GEN-LAST:event_classesListValueChanged

    private void addBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBtn1ActionPerformed
    if(classNameField.getText().equals("")){
      Toolkit.getDefaultToolkit().beep();
      JOptionPane.showMessageDialog(this,"Kindly Insert Class Name");
      return;
    }else
        addClasses();
    }//GEN-LAST:event_addBtn1ActionPerformed
    private void updateBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateBtn1ActionPerformed
        updateClasses();
    }//GEN-LAST:event_updateBtn1ActionPerformed
    private void deleteBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBtn1ActionPerformed
        Toolkit.getDefaultToolkit().beep();         
        int confrim=JOptionPane.showConfirmDialog(this,"Are you Sure to Delere Recod..?","Message",JOptionPane.YES_NO_OPTION);
         if(confrim==0)
        deleteClasses();
    }//GEN-LAST:event_deleteBtn1ActionPerformed

    private void clearBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearBtn1ActionPerformed
    clearFiled();
    }//GEN-LAST:event_clearBtn1ActionPerformed

    private void classNameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_classNameFieldActionPerformed
    }//GEN-LAST:event_classNameFieldActionPerformed

    private void exitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitBtnActionPerformed
       dispose();
    }//GEN-LAST:event_exitBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ClassDetailsFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ClassDetailsFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ClassDetailsFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ClassDetailsFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ClassDetailsFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBtn1;
    private javax.swing.JTextField classKeywordField;
    private javax.swing.JTextField classNameField;
    private javax.swing.JList<beans.ClassesBean> classesList;
    private javax.swing.JButton clearBtn1;
    private javax.swing.JButton deleteBtn1;
    private javax.swing.JButton exitBtn;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel62;
    private javax.swing.JLabel jLabel63;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTextField remarksField;
    private javax.swing.JButton updateBtn1;
    // End of variables declaration//GEN-END:variables
}

