/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package jFrames;

import beans.*;
import DBManager.DatabaseManager;
import java.awt.Toolkit;
import java.util.Vector;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;

/**
 *
 * @author IB
 */

public class SchemeDetailsFrame extends javax.swing.JFrame {

    /**
     * Creates new form SchemeDetailsFrame
     */
    public SchemeDetailsFrame() {
        initComponents();
        try{
             Vector classesVec=DatabaseManager.getClasses();
             loadComboBox(classesVec,classCombo);
        }catch(Exception e){
            e.printStackTrace();
        }
    }
    
   private void loadComboBox(Vector<Object> obj,JComboBox combo){
        if(obj!=null)
         for(Object o:obj)
           combo.addItem(o);
    }
private void addSchem(){
    ClassesBean classBean=(ClassesBean)classCombo.getSelectedItem();
    if(classBean==null)return;
    SchemeBean schemeBean=new SchemeBean();
    schemeBean.setClassId(classBean.getClassId());
    schemeBean.setSchemeName(schemeField.getText());
    schemeBean.setStatus(1);
    schemeBean.setLastUpdate("");
    schemeBean.setMaxMarks(0);
    schemeBean.setMinMarks(0);
    try{
        int rows=DatabaseManager.addScheme(schemeBean);
          if(rows>0)JOptionPane.showMessageDialog(this,"Record Insert Sucessfully..");
          getListScheme();
        }catch(Exception e){
            e.printStackTrace();
        }
    }
private void getListScheme(){
      try{
       ClassesBean classBean=(ClassesBean)classCombo.getSelectedItem();
       if(classBean==null)return;
        Vector v=DatabaseManager.getSchemeByClassId(classBean.getClassId());
         schemesList.setListData(v);
        }catch(Exception e){
            e.printStackTrace();
        }
    }
    
 private void deleteScheme(){   
    SchemeBean schemeBean=(SchemeBean)schemesList.getSelectedValue();
   if(schemeBean==null){ 
        Toolkit.getDefaultToolkit().beep();   
        JOptionPane.showMessageDialog(this,"Kindly Select Scheme From List.."); 
        return;
        }else
        try{
            int rows=DatabaseManager.deleteSchemeBySchemeId(schemeBean.getSchemeId());
            if(rows>0)JOptionPane.showMessageDialog(this,"Delete Sucessfully...");
              getListScheme(); 
              clearFiled();
          }catch(Exception e){
              e.printStackTrace();
          }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel36 = new javax.swing.JLabel();
        updateBtn2 = new javax.swing.JButton();
        addBtn2 = new javax.swing.JButton();
        schemeField = new javax.swing.JTextField();
        clearBtn2 = new javax.swing.JButton();
        remarksField2 = new javax.swing.JTextField();
        jLabel32 = new javax.swing.JLabel();
        jLabel61 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        classCombo = new javax.swing.JComboBox<beans.ClassesBean>();
        deleteBtn2 = new javax.swing.JButton();
        exitBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        schemesList = new javax.swing.JList();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Scheme Details");
        setResizable(false);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Scheme Details", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Courier New", 1, 12))); // NOI18N

        jLabel36.setFont(new java.awt.Font("Courier New", 1, 16)); // NOI18N
        jLabel36.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel36.setText("Class:");

        updateBtn2.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        updateBtn2.setText("UPDATE");
        updateBtn2.setEnabled(true);
        updateBtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateBtn2ActionPerformed(evt);
            }
        });

        addBtn2.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        addBtn2.setText("ADD");
        addBtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBtn2ActionPerformed(evt);
            }
        });

        schemeField.setFont(new java.awt.Font("Courier New", 1, 16)); // NOI18N

        clearBtn2.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        clearBtn2.setText("CLEAR");
        clearBtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearBtn2ActionPerformed(evt);
            }
        });

        remarksField2.setFont(new java.awt.Font("Courier New", 1, 16)); // NOI18N

        jLabel32.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        jLabel32.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel32.setText("Course Schemes");

        jLabel61.setFont(new java.awt.Font("Courier New", 1, 16)); // NOI18N
        jLabel61.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel61.setText("Remarks:");

        jLabel46.setFont(new java.awt.Font("Courier New", 1, 16)); // NOI18N
        jLabel46.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel46.setText("Scheme:");

        classCombo.setFont(new java.awt.Font("Courier New", 1, 16)); // NOI18N
        classCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                classComboActionPerformed(evt);
            }
        });

        deleteBtn2.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        deleteBtn2.setText("DELETE");
        deleteBtn2.setEnabled(true);
        deleteBtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBtn2ActionPerformed(evt);
            }
        });

        exitBtn.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        exitBtn.setText("EXIT");
        exitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitBtnActionPerformed(evt);
            }
        });

        schemesList.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        schemesList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                schemesListValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(schemesList);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel61)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(addBtn2, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(2, 2, 2)
                                .addComponent(updateBtn2)
                                .addGap(2, 2, 2)
                                .addComponent(deleteBtn2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(clearBtn2, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(exitBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(remarksField2, javax.swing.GroupLayout.PREFERRED_SIZE, 409, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel36, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel46, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(schemeField)
                            .addComponent(classCombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel32, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(77, 77, 77))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel32, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel36, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(classCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel46, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(schemeField))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 174, Short.MAX_VALUE)
                        .addComponent(jLabel61)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(remarksField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(addBtn2)
                            .addComponent(updateBtn2)
                            .addComponent(deleteBtn2)
                            .addComponent(clearBtn2)
                            .addComponent(exitBtn)))
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 692, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void clearBtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearBtn2ActionPerformed
        clearFiled();
    }//GEN-LAST:event_clearBtn2ActionPerformed

    private void clearFiled(){
    schemeField.setText("");
    remarksField2.setText("");
    }
    private void classComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_classComboActionPerformed
      getListScheme();
    }//GEN-LAST:event_classComboActionPerformed

    private void deleteBtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBtn2ActionPerformed
        Toolkit.getDefaultToolkit().beep();  
        int opt=JOptionPane.showConfirmDialog(this,"Are Sure To Delete Scheme.","Delete Message",JOptionPane.YES_NO_OPTION);
        if(opt==0)
         deleteScheme();
    }//GEN-LAST:event_deleteBtn2ActionPerformed
    
    private void addBtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBtn2ActionPerformed
    if(schemeField.getText().equals("")){
         Toolkit.getDefaultToolkit().beep();   
          JOptionPane.showMessageDialog(this,"Kindly Insert Scheme In Filed "); 
          return;
       }else 
        addSchem();
    }//GEN-LAST:event_addBtn2ActionPerformed

    private void updateBtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateBtn2ActionPerformed
    SchemeBean schemeBean=(SchemeBean)schemesList.getSelectedValue();
    if(schemeBean==null){
        Toolkit.getDefaultToolkit().beep();   
        JOptionPane.showMessageDialog(this,"Kindly Select Scheme From List..."); return;}
        try{
            schemeBean.setSchemeName(schemeField.getText());
            int rows=DatabaseManager.updateSchemeByClassId(schemeBean, schemeBean.getClassId());
            if(rows>0)JOptionPane.showMessageDialog(this,"Record Update Sucessfully...");
            getListScheme();
        }catch(Exception e){e.printStackTrace();}
    }//GEN-LAST:event_updateBtn2ActionPerformed
    
    private void exitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitBtnActionPerformed
        dispose();
    }//GEN-LAST:event_exitBtnActionPerformed

    private void schemesListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_schemesListValueChanged
       SchemeBean schemeBean=(SchemeBean)schemesList.getSelectedValue();
         if(schemeBean==null)return;
         schemeField.setText(schemeBean.getSchemeName());
    }//GEN-LAST:event_schemesListValueChanged

    /**
     * @param args the command line arguments
     */
public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SchemeDetailsFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SchemeDetailsFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SchemeDetailsFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SchemeDetailsFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SchemeDetailsFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBtn2;
    private javax.swing.JComboBox<beans.ClassesBean> classCombo;
    private javax.swing.JButton clearBtn2;
    private javax.swing.JButton deleteBtn2;
    private javax.swing.JButton exitBtn;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField remarksField2;
    private javax.swing.JTextField schemeField;
    private javax.swing.JList schemesList;
    private javax.swing.JButton updateBtn2;
    // End of variables declaration//GEN-END:variables
}

