/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jFrames;

import beans.*;
import java.util.Vector;
import javax.swing.JComboBox;
import DBManager.DatabaseManager;
import java.awt.Toolkit;
import javax.swing.JOptionPane;

/**
 *
 * @author IB
 */

public class SubjectDetailsFrame extends javax.swing.JFrame {

    /**
     * Creates new form SubjectDetailsFrame
     */

    public SubjectDetailsFrame() {
        initComponents();
        try{
            Vector v=DatabaseManager.getAllScheme();
             loadComboBox(v,schemeCombo);
        }catch(Exception e){
            e.printStackTrace();
        }
    }
     private void loadComboBox(Vector<Object> obj,JComboBox combo){
        if(obj!=null)
         for(Object o:obj)
         combo.addItem(o);
    }
     
     private void getCourseList(){
        beans.SchemeBean bean=(beans.SchemeBean)schemeCombo.getSelectedItem();
        if(bean==null)return;
            try{
            java.util.Vector v=DatabaseManager.getCoursesByClassId(bean.getClassId(),bean.getSchemeId());
            subjectsList.setListData(v);
            }catch(Exception e){
             e.printStackTrace();
            }//End of trycatch
     }
     
private void addSubject(){
   beans.CourseBean courseBean=getFieldData(); 
   if(courseBean==null)return;
    try{
       int rows=DatabaseManager.addCourse(courseBean);
        if(rows>0){Toolkit.getDefaultToolkit().beep(); JOptionPane.showMessageDialog(this,"Record Insert Sucessfully...");}
        getCourseList();
        clearFiled();
        }catch(Exception e){
        e.printStackTrace();
        }
       }
        
private void clearFiled(){
    subjectNameField.setText("");
    subjectkeywordField.setText("");
    minMarksField1.setText("");
    maxMarksField1.setText("");
    getCourseList();
    }

private beans.CourseBean getFieldData(){
    SchemeBean schemeBean=(SchemeBean)schemeCombo.getSelectedItem();
    CourseBean courseBean=new CourseBean();
    courseBean.setSchemeId(schemeBean.getSchemeId());
    courseBean.setClassId(schemeBean.getClassId());
    courseBean.setCourseTitle(subjectNameField.getText());
    courseBean.setCourseKeyword(subjectkeywordField.getText());
    courseBean.setSubjectType((String)subjectTypeCombo.getSelectedItem());
    courseBean.setMinMarks(Integer.parseInt(minMarksField1.getText()));
    courseBean.setMaxMarks(Integer.parseInt(maxMarksField1.getText()));
    courseBean.setStatus(1);
  return courseBean;
}
    
 private void deleteSubjectDetails(){
       CourseBean bean=(CourseBean)subjectsList.getSelectedValue();
      if(bean==null){ Toolkit.getDefaultToolkit().beep();JOptionPane.showMessageDialog(this,"Select Subject To Delete Record."); return;}
       Toolkit.getDefaultToolkit().beep();
      int confrim=JOptionPane.showConfirmDialog(this,"Are You Sure To Delete Record?","Message",JOptionPane.YES_NO_OPTION);
      if(confrim==0){
      try{
          int rows=DatabaseManager.deleteCourseByCourseNo(bean.getCourseNo());
          if(rows>0)JOptionPane.showMessageDialog(this,"Record Delete Sucessfully..");
          clearFiled();
           getCourseList();  
      }catch(Exception e){
          e.printStackTrace();
        }
      }// end of if      
    }
    
 private void updateSubject(){
 CourseBean courseBean=(CourseBean)subjectsList.getSelectedValue();
   if(courseBean==null)return;
   
   CourseBean fieldData=getFieldData();
   
   try{
      int rows=DatabaseManager.updateCourseByCourseNo(fieldData, courseBean.getCourseNo());
      if(rows>0){Toolkit.getDefaultToolkit().beep(); JOptionPane.showMessageDialog(this,"Record Update Scuessfully...");}
      getCourseList();
       }catch(Exception e){
        e.printStackTrace();
    }
  }

 /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        schemeCombo = new javax.swing.JComboBox<beans.SchemeBean>();
        updateBtn3 = new javax.swing.JButton();
        subjectNameField = new javax.swing.JTextField();
        jLabel35 = new javax.swing.JLabel();
        subjectTypeCombo = new javax.swing.JComboBox<String>();
        subjectkeywordField = new javax.swing.JTextField();
        jLabel44 = new javax.swing.JLabel();
        remarksField3 = new javax.swing.JTextField();
        addBtn3 = new javax.swing.JButton();
        jLabel43 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        maxMarksField1 = new javax.swing.JTextField();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        minMarksField1 = new javax.swing.JTextField();
        jLabel40 = new javax.swing.JLabel();
        jLabel64 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        subjectsList = new javax.swing.JList<beans.CourseBean>();
        deleteBtn3 = new javax.swing.JButton();
        jLabel42 = new javax.swing.JLabel();
        clearBtn3 = new javax.swing.JButton();
        exitBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Subject Details");
        setResizable(false);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Subject Details", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Courier New", 1, 12))); // NOI18N

        schemeCombo.setFont(new java.awt.Font("Courier New", 1, 16)); // NOI18N
        schemeCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                schemeComboActionPerformed(evt);
            }
        });

        updateBtn3.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        updateBtn3.setText("UPDATE");
        updateBtn3.setEnabled(true);
        updateBtn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateBtn3ActionPerformed(evt);
            }
        });

        subjectNameField.setFont(new java.awt.Font("Courier New", 1, 16)); // NOI18N

        jLabel35.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        jLabel35.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel35.setText("Subjects");

        subjectTypeCombo.setFont(new java.awt.Font("Courier New", 1, 16)); // NOI18N
        subjectTypeCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {"Compulsory Th","Compulsory Lab","Theory","Practical",}));
        subjectTypeCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subjectTypeComboActionPerformed(evt);
            }
        });

        subjectkeywordField.setFont(new java.awt.Font("Courier New", 1, 16)); // NOI18N

        jLabel44.setFont(new java.awt.Font("Courier New", 1, 16)); // NOI18N
        jLabel44.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel44.setText("SubType:");

        remarksField3.setFont(new java.awt.Font("Courier New", 1, 16)); // NOI18N

        addBtn3.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        addBtn3.setText("ADD");
        addBtn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBtn3ActionPerformed(evt);
            }
        });

        jLabel43.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        jLabel43.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel43.setText("SubKeyword:");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Marks", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Courier New", 1, 12))); // NOI18N

        maxMarksField1.setFont(new java.awt.Font("Courier New", 1, 16)); // NOI18N

        jLabel37.setFont(new java.awt.Font("Courier New", 1, 16)); // NOI18N
        jLabel37.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel37.setText("Min:");

        jLabel38.setFont(new java.awt.Font("Courier New", 1, 16)); // NOI18N
        jLabel38.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel38.setText("Max:");

        minMarksField1.setFont(new java.awt.Font("Courier New", 1, 16)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel37)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(minMarksField1, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel38, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(maxMarksField1, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(minMarksField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel37)
                    .addComponent(jLabel38)
                    .addComponent(maxMarksField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jLabel40.setFont(new java.awt.Font("Courier New", 1, 16)); // NOI18N
        jLabel40.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel40.setText("Scheme:");

        jLabel64.setFont(new java.awt.Font("Courier New", 1, 16)); // NOI18N
        jLabel64.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel64.setText("Remarks:");

        subjectsList.setFont(new java.awt.Font("Courier New", 1, 16)); // NOI18N
        subjectsList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                subjectsListValueChanged(evt);
            }
        });
        jScrollPane6.setViewportView(subjectsList);

        deleteBtn3.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        deleteBtn3.setText("DELETE");
        deleteBtn3.setEnabled(true);
        deleteBtn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBtn3ActionPerformed(evt);
            }
        });

        jLabel42.setFont(new java.awt.Font("Courier New", 1, 16)); // NOI18N
        jLabel42.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel42.setText("Subject:");

        clearBtn3.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        clearBtn3.setText("CLEAR");
        clearBtn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearBtn3ActionPerformed(evt);
            }
        });

        exitBtn.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        exitBtn.setText("EXIT");
        exitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel44, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel42, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel43, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(4, 4, 4)
                                        .addComponent(subjectNameField))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(4, 4, 4)
                                        .addComponent(subjectkeywordField))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(subjectTypeCombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel40, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(schemeCombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(100, 100, 100))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jLabel64))
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(remarksField3, javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(addBtn3, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(6, 6, 6)
                                    .addComponent(updateBtn3)
                                    .addGap(2, 2, 2)
                                    .addComponent(deleteBtn3)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(clearBtn3, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(exitBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel35, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel35, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel40)
                            .addComponent(schemeCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel42)
                            .addComponent(subjectNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(5, 5, 5)
                                .addComponent(jLabel43))
                            .addComponent(subjectkeywordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel44, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(subjectTypeCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(9, 9, 9)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                        .addComponent(jLabel64, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(remarksField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(addBtn3)
                            .addComponent(updateBtn3)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(deleteBtn3)
                                .addComponent(clearBtn3)
                                .addComponent(exitBtn))))
                    .addComponent(jScrollPane6))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void schemeComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_schemeComboActionPerformed
    getCourseList();      
    }//GEN-LAST:event_schemeComboActionPerformed

    private void addBtn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBtn3ActionPerformed
      if(subjectNameField.getText().equals("")){
          Toolkit.getDefaultToolkit().beep();
          JOptionPane.showMessageDialog(this,"Kindly Insert Subject Name..");
      }else  
        addSubject();
    }//GEN-LAST:event_addBtn3ActionPerformed

    private void subjectTypeComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subjectTypeComboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_subjectTypeComboActionPerformed

    private void subjectsListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_subjectsListValueChanged
        CourseBean bean=(CourseBean)subjectsList.getSelectedValue();
        if(bean==null)return;
        subjectNameField.setText(bean.getCourseTitle());
        subjectkeywordField.setText(bean.getCourseKeyword());
        subjectTypeCombo.getModel().setSelectedItem(bean.getSubjectType());
        minMarksField1.setText(""+bean.getMinMarks());
        maxMarksField1.setText(""+bean.getMaxMarks());
    }//GEN-LAST:event_subjectsListValueChanged

    private void clearBtn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearBtn3ActionPerformed
            clearFiled();
    }//GEN-LAST:event_clearBtn3ActionPerformed

    private void updateBtn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateBtn3ActionPerformed
    updateSubject();
    }//GEN-LAST:event_updateBtn3ActionPerformed

    private void deleteBtn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBtn3ActionPerformed
        deleteSubjectDetails();
    }//GEN-LAST:event_deleteBtn3ActionPerformed

    private void exitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitBtnActionPerformed
        dispose();
    }//GEN-LAST:event_exitBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SubjectDetailsFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SubjectDetailsFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SubjectDetailsFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SubjectDetailsFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SubjectDetailsFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBtn3;
    private javax.swing.JButton clearBtn3;
    private javax.swing.JButton deleteBtn3;
    private javax.swing.JButton exitBtn;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel64;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTextField maxMarksField1;
    private javax.swing.JTextField minMarksField1;
    private javax.swing.JTextField remarksField3;
    private javax.swing.JComboBox<beans.SchemeBean> schemeCombo;
    private javax.swing.JTextField subjectNameField;
    private javax.swing.JComboBox<String> subjectTypeCombo;
    private javax.swing.JTextField subjectkeywordField;
    private javax.swing.JList<beans.CourseBean> subjectsList;
    private javax.swing.JButton updateBtn3;
    // End of variables declaration//GEN-END:variables
}

