/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jFrames;

import beans.*;
import java.util.Vector;
import javax.swing.JComboBox;
import DBManager.DatabaseManager;
import java.awt.Toolkit;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author IB
 */

public class TermDetailsFrame extends javax.swing.JFrame {

    /**
     * Creates new form TermDetailsFrame
     */
    public TermDetailsFrame() {
        initComponents();
        try{
            
            Vector classesBean=DatabaseManager.getClasses();
             loadComboBox(classesBean,classCombo);
        }catch(Exception e){
            e.printStackTrace();
        }
    }
    
        private void loadComboBox(Vector<Object> obj,JComboBox combo){
        if(obj!=null)
          for(Object o:obj)
            combo.addItem(o);
    }
   
        
        private void getTermList(int classId,int schemeId){
            try{ 
         Vector term=DatabaseManager.getTermByClassId(classId,schemeId);
            termList.setListData(term);
            }catch(Exception e){
                e.printStackTrace();
            }
        }
        
 private void addTerm(int classId,int schemeId,int term,int termMonth){
            TermBean termBean=new TermBean();
            termBean.setClassId(classId);
            termBean.setSchemeId(schemeId);
            termBean.setTerm(term);
            termBean.setTermMonth(termMonth);
            termBean.setStatus(1);
            termBean.setRemarks(remarksField.getText());
             try {
                   int rows=DatabaseManager.addTerm(termBean);
                    if(rows>0)
                     JOptionPane.showMessageDialog(this,"Recod Insert Sucessfully...");
                     getTermList(classId,schemeId);
            } catch (SQLException ex) {
                 Toolkit.getDefaultToolkit().beep();
                JOptionPane.showMessageDialog(this,"This Term is Alread Insert in This Class");
                Logger.getLogger(TermDetailsFrame.class.getName()).log(Level.SEVERE, null, ex);
         }
  }
        
 private void deleteTerm(){
  SchemeBean schemeBean=(SchemeBean)schemeCombo.getSelectedItem();
  TermBean termBean=(TermBean)termList.getSelectedValue();
  if(termBean==null){
    Toolkit.getDefaultToolkit().beep(); 
    JOptionPane.showMessageDialog(this,"Kindly Select Student From List..");
    return;
  }
  
 try{
     int rows=DatabaseManager.deleteTermBySchemeId(schemeBean.getSchemeId(),termBean.getTerm());
     if(rows>0){
           Toolkit.getDefaultToolkit().beep();
         JOptionPane.showMessageDialog(this,"Delete Sucessfully...");
         getTermList(schemeBean.getClassId(), schemeBean.getSchemeId());
     }
 }catch(Exception e){
     e.printStackTrace();
 }
}
        
            
        

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        updateBtn4 = new javax.swing.JButton();
        jLabel48 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        clearBtn4 = new javax.swing.JButton();
        classCombo = new javax.swing.JComboBox<beans.ClassesBean>();
        deleteBtn4 = new javax.swing.JButton();
        jLabel65 = new javax.swing.JLabel();
        remarksField = new javax.swing.JTextField();
        termMonthCombo = new javax.swing.JComboBox<String>();
        addBtn4 = new javax.swing.JButton();
        jLabel50 = new javax.swing.JLabel();
        exitBtn = new javax.swing.JButton();
        jLabel52 = new javax.swing.JLabel();
        termCombo = new javax.swing.JComboBox<String>();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        termList = new javax.swing.JList();
        monthTextField = new javax.swing.JTextField();
        jLabel51 = new javax.swing.JLabel();
        schemeCombo = new javax.swing.JComboBox<beans.ClassesBean>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Term Details");
        setResizable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Term Details", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Courier New", 1, 12))); // NOI18N

        updateBtn4.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        updateBtn4.setText("UPDATE");
        updateBtn4.setEnabled(false);
        updateBtn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateBtn4ActionPerformed(evt);
            }
        });

        jLabel48.setFont(new java.awt.Font("Courier New", 1, 16)); // NOI18N
        jLabel48.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel48.setText("Class:");

        jLabel49.setFont(new java.awt.Font("Courier New", 1, 16)); // NOI18N
        jLabel49.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel49.setText("Term:");

        clearBtn4.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        clearBtn4.setText("CLEAR");
        clearBtn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearBtn4ActionPerformed(evt);
            }
        });

        classCombo.setFont(new java.awt.Font("Courier New", 1, 16)); // NOI18N
        classCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                classComboActionPerformed(evt);
            }
        });

        deleteBtn4.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        deleteBtn4.setText("DELETE");
        deleteBtn4.setEnabled(true);
        deleteBtn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBtn4ActionPerformed(evt);
            }
        });

        jLabel65.setFont(new java.awt.Font("Courier New", 1, 16)); // NOI18N
        jLabel65.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel65.setText("Remarks:");

        remarksField.setFont(new java.awt.Font("Courier New", 1, 16)); // NOI18N

        termMonthCombo.setFont(new java.awt.Font("Courier New", 1, 16)); // NOI18N
        termMonthCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec" }));
        termMonthCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                termMonthComboActionPerformed(evt);
            }
        });

        addBtn4.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        addBtn4.setText("ADD");
        addBtn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBtn4ActionPerformed(evt);
            }
        });

        jLabel50.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        jLabel50.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel50.setText("Terms");

        exitBtn.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        exitBtn.setText("EXIT");
        exitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitBtnActionPerformed(evt);
            }
        });

        jLabel52.setFont(new java.awt.Font("Courier New", 1, 16)); // NOI18N
        jLabel52.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel52.setText("Term Month:");

        termCombo.setFont(new java.awt.Font("Courier New", 1, 16)); // NOI18N
        termCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2" }));
        termCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                termComboActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Courier New", 1, 16)); // NOI18N
        jLabel2.setText("Month:");

        termList.setFont(new java.awt.Font("Courier New", 1, 16)); // NOI18N
        termList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                termListValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(termList);

        monthTextField.setFont(new java.awt.Font("Courier New", 1, 16)); // NOI18N
        monthTextField.setEnabled(false);

        jLabel51.setFont(new java.awt.Font("Courier New", 1, 16)); // NOI18N
        jLabel51.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel51.setText("Scheme:");

        schemeCombo.setFont(new java.awt.Font("Courier New", 1, 16)); // NOI18N
        schemeCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                schemeComboActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel48)
                            .addComponent(jLabel51))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(classCombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(schemeCombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel65)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(remarksField, javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(addBtn4, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(2, 2, 2)
                                    .addComponent(updateBtn4)
                                    .addGap(2, 2, 2)
                                    .addComponent(deleteBtn4)
                                    .addGap(6, 6, 6)
                                    .addComponent(clearBtn4)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(exitBtn))))
                        .addGap(0, 25, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel49)
                            .addComponent(jLabel52))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(termMonthCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(termCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(monthTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel50, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel50)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(jLabel48, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(classCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel51, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(schemeCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel52, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(termMonthCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel49, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(termCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(monthTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel65)
                        .addGap(6, 6, 6)
                        .addComponent(remarksField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(addBtn4)
                            .addComponent(updateBtn4)
                            .addComponent(deleteBtn4)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(clearBtn4)
                                .addComponent(exitBtn))))
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void addBtn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBtn4ActionPerformed
        int classId=((ClassesBean)classCombo.getSelectedItem()).getClassId();
        int schemeId=((SchemeBean)schemeCombo.getSelectedItem()).getSchemeId();
        String month=(String)termMonthCombo.getSelectedItem();
        int term = Integer.parseInt((String) termCombo.getSelectedItem());
       String month_Name[]={"Jan","Feb", "Mar"," Apr" ,"May","Jun" ,"Jul" ,"Aug" ,"Sep", "Oct", "Nov","Dec"};
        for(int i=0; i<termMonthCombo.getItemCount(); i++){     
        if(month.equals(month_Name[i])){
        int termMonth=i+1;
        addTerm(classId,schemeId,term,termMonth);
               }
        }
    }//GEN-LAST:event_addBtn4ActionPerformed

  
    private void updateBtn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateBtn4ActionPerformed
       
    }//GEN-LAST:event_updateBtn4ActionPerformed

    private void classComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_classComboActionPerformed
        ClassesBean classBean=(ClassesBean)classCombo.getSelectedItem();
   if(classBean==null)return; 
   try{
       schemeCombo.removeAllItems();
       Vector v=DatabaseManager.getSchemeByClassId(classBean.getClassId());
         loadComboBox(v,schemeCombo);
   }catch(Exception e){
       e.printStackTrace();
   }
   SchemeBean schemBean=(SchemeBean)schemeCombo.getSelectedItem();
   if(schemBean==null)return;
    getTermList(classBean.getClassId(),schemBean.getSchemeId());
        
    }//GEN-LAST:event_classComboActionPerformed

    private void deleteBtn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBtn4ActionPerformed
        Toolkit.getDefaultToolkit().beep();
        int opt=JOptionPane.showConfirmDialog(this,"Are You Sure Want to Delete...?","Delete Message",JOptionPane.YES_NO_OPTION);
        if(opt==0)
        deleteTerm();    
    }//GEN-LAST:event_deleteBtn4ActionPerformed

 
    
    private void clearBtn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearBtn4ActionPerformed
     remarksField.setText("");
     monthTextField.setText("");
    }//GEN-LAST:event_clearBtn4ActionPerformed

    private void termMonthComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_termMonthComboActionPerformed
                
    }//GEN-LAST:event_termMonthComboActionPerformed

    private void exitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitBtnActionPerformed
        dispose();
    }//GEN-LAST:event_exitBtnActionPerformed

    private void termComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_termComboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_termComboActionPerformed

    private void termListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_termListValueChanged
      TermBean termBean=(TermBean)termList.getSelectedValue();
      if(termBean==null)return;
       String month_Name[]={"Jan","Feb", "Mar"," Apr" ,"May","Jun" ,"Jul" ,"Aug" ,"Sep", "Oct", "Nov","Dec"};
      for(int i=0; i<month_Name.length; i++){
          if(termBean.getTermMonth()==i)
             monthTextField.setText(month_Name[i-1]);
      }
    
    }//GEN-LAST:event_termListValueChanged

    private void schemeComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_schemeComboActionPerformed
    ClassesBean classBean=(ClassesBean)classCombo.getSelectedItem();
   if(classBean==null)return;
   SchemeBean schemBean=(SchemeBean)schemeCombo.getSelectedItem();
   if(schemBean==null)return;
    getTermList(classBean.getClassId(),schemBean.getSchemeId());
        
    }//GEN-LAST:event_schemeComboActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TermDetailsFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TermDetailsFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TermDetailsFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TermDetailsFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TermDetailsFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBtn4;
    private javax.swing.JComboBox<beans.ClassesBean> classCombo;
    private javax.swing.JButton clearBtn4;
    private javax.swing.JButton deleteBtn4;
    private javax.swing.JButton exitBtn;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel65;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField monthTextField;
    private javax.swing.JTextField remarksField;
    private javax.swing.JComboBox<beans.ClassesBean> schemeCombo;
    private javax.swing.JComboBox<String> termCombo;
    private javax.swing.JList termList;
    private javax.swing.JComboBox<String> termMonthCombo;
    private javax.swing.JButton updateBtn4;
    // End of variables declaration//GEN-END:variables
}

